### ISSUE TITLE
[suggestion] return reason for ignore

### ISSUE THREAD

**Issue by phanirithvij** [sabhiram/go-gitignore#11]
So I'm suggesting one more sibling method for `MatchesPath` which should kind of function like

```sh
git check-ignore -v filename
```

i.e. It would be cool if it can return

- Which of the patterns matches with it (should be easy to implement right now)
- Where the pattern was defined in the .gitignore file (needs a lot of work I assume)

**Comment by sabhiram** [comment]
Thank you for this, added feedback in the PR.
