### ISSUE TITLE
Could you add a tag?

### ISSUE THREAD

**Issue by drgarcia1986** [sabhiram/go-gitignore#8]
First of all thanks for the great work 👍 

I'll use `go-gitignore` in one of my projects and would be nice if the project follows semver tagging style.

**Comment by sabhiram** [comment]
absolutely can do :) give me a few minutes - sorry I did not see this till today.

**Comment by sabhiram** [comment]
Done - ill add the ability for tag management via `github/sabhiram/gover` soon - for now this should be good.

**Comment by drgarcia1986** [comment]
Thank you @sabhiram 👍
