### ISSUE TITLE
Remove extraneous error return

### ISSUE THREAD

**Issue by dfreilich** [sabhiram/go-gitignore#9]
In `CompileIgnoreLines` ([here](https://github.com/sabhiram/go-gitignore/blob/master/ignore.go#L166)), the function includes an error, when there is no actual error case returned. That then forces following methods (like `CompileIgnoreFile`) to also return a possible error, when none is possible. 

Shouldn't the function call be:
```
func CompileIgnoreLines(lines ...string) *GitIgnore {
```
?

**Comment by sabhiram** [comment]
Good point - fixed - sorry I just saw this after many 🌔 s

**Comment by dfreilich** [comment]
Thank you so much for following up on this after so long, and for opening up the PR in pack 😄
